name: deploy to lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
    push:
        branches:
            - main

jobs:
    deploy_source:
        name: deploy lambda from source
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - uses: aws-actions/setup-sam@v1
            - uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            # Sam init
            - run: sam init -r python3.9

            # sam build
            - run: sam build --use-container

            # Run Unit tests- Specify unit tests here
            - run: make tests

            # sam deploy
            - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world --s3-bucket ##s3-bucket## --capabilities CAPABILITY_IAM --region ##region##
